# \u2705 CORRECT - Add // after mysql:
spring.datasource.url=jdbc:mysql://root:HNWHSTCmkBEAyXHidBGdHTQzIxarxnaj@switchyard.proxy.rlwy.net:37052/project_service
spring.datasource.username=root
spring.datasource.password=HOZVdTayISMCWVuZwctQsBjvWuJBfPtZ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect






# OAuth2 Configuration - Development
spring.security.oauth2.client.registration.google.client-id=970144426768-3ohd73ork5shqubem7v13j6kepk4u7fq.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=https://project-mgmt-backend-production-b1d3.up.railway.app/login/oauth2/code/google

spring.security.oauth2.client.registration.github.client-id=Ov23liVJssOWyxFx8PhK
spring.security.oauth2.client.registration.github.client-secret=c47919f37c19e5a8c16471479bdba3443625619a
spring.security.oauth2.client.registration.github.scope=user:email
spring.security.oauth2.client.registration.github.redirect-uri=https://project-mgmt-backend-production-b1d3.up.railway.app/login/oauth2/code/github



